CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
    age INT,
    PRIMARY KEY (id)
);

CREATE TABLE m_companies (
    id int NOT NULL AUTO_INCREMENT,
    company_name varchar(100),
    post_code varchar(8),
    address_pref varchar(100),
    address_city varchar(100),
    address_other varchar(100),
    facility_name varchar(100),
    tell varchar(20),
    ceo varchar(50),
    capital varchar(15),
    pay_cutoff_date varchar(2),
    pay_date varchar(2),
    empl_insur_apply_office_num varchar(13),
    empl_insur_estab_date date,
    labor_insur_num varchar(15),
    labor_insur_estab_date date,
    social_insur_num varchar(6),
    social_insur_estab_date date,
    welfare_pension_insur_office_num varchar(4),
    corporate_num varchar(13),
    industry_class tinyint,
    industry_type varchar(30),
    start date,
    paidleave_cutoff_date varchar(5),
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_employees (
    id int NOT NULL AUTO_INCREMENT,
    employee_num varchar(15),
    idm varchar(20),
    shift_id int,
    name varchar(50),
    name_kana varchar(100),
    birthday date,
    in_company date,
    exit_company date,
    sex tinyint,
    weekly_work_time decimal,
    post_code varchar(8),
    address_pref varchar(100),
    address_city varchar(100),
    address_other varchar(100),
    tell varchar(20),
    empl_insur_insured_num varchar(13),
    pension_num varchar(10),
    mynumber varchar(12),
    former_job varchar(100),
    dependent tinyint,
    health_insur_num varchar(15),
    nationality varchar(40),
    empl_insur_insur_qual_acq_date date,
    empl_insur_insur_qual_lost_date date,
    soc_insur_insur_qual_acq_date date,
    soc_insur_insur_qual_lost_date date,
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    memo varchar(100),
    PRIMARY KEY (id)
);

CREATE TABLE m_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    base int,
    salary_type int,
    std_monthly_compensation int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    income_tax int,
    inhabitant_tax int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_calendar (
    id int NOT NULL AUTO_INCREMENT,
    ymd date,
    year int,
    month int,
    day int,
    day_of_week varchar(3),
    visible_flg tinyint,
    working_st tinyint,
    memo varchar(100),
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_jobshift (
    id int NOT NULL AUTO_INCREMENT,
    shift_name varchar(40),
    delete_flg tinyint,
    job_type int,
    work_in_time time,
    work_out_time time,
    rest time,
    memo varchar(99),
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_admin (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    login_id varchar(30),
    password varchar(200),
    fail_count int,
    edit_flg tinyint,
    attend_flg tinyint,
    leave_flg tinyint,
    employee_flg tinyint,
    calendar_flg tinyint,
    shift_flg tinyint,
    payment_flg tinyint,
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_leavemanage (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    remain_day tinyint,
    add_day tinyint,
    memo varchar(400),
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_attends (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    dete date,
    working_st tinyint,
    round_work_in_time datetime,
    work_in datetime,
    round_work_out_time datetime,
    work_out datetime,
    work_time time,
    rest time,
    overtime time,
    nighttime time,
    holiday_time time,
    create_at datetime,
    create_acc int,
    create_mac varchar(20),
    update_at datetime,
    update_acc int,
    update_mac varchar(20),
    PRIMARY KEY (id)
);

CREATE TABLE t_leaverequest (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    request_date date,
    target_date date,
    subm_st tinyint,
    authorizer int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    payment_date date,
    income int,
    base int,
    overtime_pay int,
    nighttime_pay int,
    holiday_pay int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    employee_insur int,
    income_tax int,
    inhabitant_tax int,
    withholding_tax int,
    adj_pay int,
    others int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);