CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
    age INT,
    PRIMARY KEY (id)
);

CREATE TABLE m_companies (
    id int NOT NULL AUTO_INCREMENT,
    company_name varchar,
    post_code varchar(8),
    address_pref varchar,
    address_city varchar,
    address_other varchar,
    facility_name varchar,
    tell varchar,
    ceo varchar,
    capital varchar,
    pay_cutoff_date varchar,
    pay_date varchar,
    empl_insur_apply_office_num varchar(13),
    empl_insur_estab_date date,
    labor_insur_num varchar(15),
    labor_insur_estab_date date,
    social_insur_num varchar(6),
    social_insur_estab_date date,
    welfare_pension_insur_office_num varchar,
    corporate_num varchar(13),
    industry_class tinyint,
    industry_type varchar,
    start date,
    paidleave_cutoff_date varchar,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_employees (
    id int NOT NULL AUTO_INCREMENT,
    employee_num varchar,
    idm varchar,
    shift_id int,
    name varchar,
    name_kana varchar,
    birthday date,
    in_company date,
    exit_company date,
    sex tinyint,
    weekly_work_time decimal,
    post_code varchar,
    address_pref varchar,
    address_city varchar,
    address_other varchar,
    tell varchar,
    empl_insur_insured_num varchar,
    pension_num varchar,
    mynumber varchar,
    former_job varchar,
    dependent tinyint,
    health_insur_num varchar,
    nationality varchar,
    empl_insur_insur_qual_acq_date date,
    empl_insur_insur_qual_lost_date date,
    soc_insur_insur_qual_acq_date date,
    soc_insur_insur_qual_lost_date date,
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    memo varchar,
    PRIMARY KEY (id)
);

CREATE TABLE m_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    base int,
    salary_type int,
    std_monthly_compensation int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    income_tax int,
    inhabitant_tax int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_calendar (
    id int NOT NULL AUTO_INCREMENT,
    ymd date,
    year int,
    month int,
    day int,
    day_of_week varchar,
    visible_flg tinyint,
    attend_st tinyint,
    memo varchar,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_jobshift (
    id int NOT NULL AUTO_INCREMENT,
    shift_name varchar,
    delete_flg tinyint,
    job_type int,
    work_in_time time,
    work_out_time time,
    rest time,
    memo varchar,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_admin (
    id int NOT NULL AUTO_INCREMENT,
    name varchar,
    login_id varchar,
    password varchar,
    fail_count int,
    edit_flg tinyint,
    attend_flg tinyint,
    leave_flg tinyint,
    employee_flg tinyint,
    calendar_flg tinyint,
    shift_flg tinyint,
    payment_flg tinyint,
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_leavemanage (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    remain_day tinyint,
    add_day tinyint,
    memo varchar,
    start date,
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_attends (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    ymd date,
    working_st tinyint,
    round_work_in_time datetime,
    work_in datetime,
    round_work_out_time datetime,
    work_out datetime,
    work_time time,
    rest time,
    overtime time,
    nighttime time,
    holiday_time time,
    create_at datetime,
    create_acc int,
    create_mac varchar,
    update_at datetime,
    update_acc int,
    update_mac varchar,
    PRIMARY KEY (id)
);

CREATE TABLE t_leaverequest (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    request_date date,
    target_date date,
    subm_st tinyint,
    authorizer int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int,
    payment_date date,
    income int,
    base int,
    overtime_pay int,
    nighttime_pay int,
    holiday_pay int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    employee_insur int,
    income_tax int,
    inhabitant_tax int,
    withholding_tax int,
    adj_pay int,
    others int,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);