CREATE TABLE m_companies (
    id int NOT NULL AUTO_INCREMENT,
    company_name varchar(100) NOT NULL,
    post_code varchar(8) NOT NULL,
    address_pref varchar(100) NOT NULL,
    address_city varchar(100) NOT NULL,
    address_other varchar(100) NOT NULL,
    facility_name varchar(100) NOT NULL,
    tell varchar(20) NOT NULL,
    ceo varchar(50) NOT NULL,
    capital varchar(15) NOT NULL,
    pay_cutoff_date varchar(2) NOT NULL,
    pay_date varchar(2) NOT NULL,
    empl_insur_apply_office_num varchar(13),
    empl_insur_estab_date date,
    labor_insur_num varchar(15),
    labor_insur_estab_date date,
    social_insur_num varchar(6),
    social_insur_estab_date date,
    welfare_pension_insur_office_num varchar(4),
    corporate_num varchar(13),
    industry_class tinyint,
    industry_type varchar(30),
    start date,
    paidvacanmt_cutoff_date varchar(5),
    end date,
    create_at datetime,
    create_acc int,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_employees (
    id int NOT NULL AUTO_INCREMENT,
    shift_id int,
    name varchar(50) NOT NULL,
    name_kana varchar(100) NOT NULL,
    birthday date NOT NULL,
    in_company date NOT NULL,
    exit_company date,
    sex tinyint NOT NULL,
    salary_type tinyint NOT NULL,
    base int NOT NULL,
    weekly_work_time decimal NOT NULL,
    std_monthly_compensation int NOT NULL,
    empl_insur_insured_num varchar(13),
    pension_num varchar(10),
    mynumber varchar(12),
    former_job varchar(100),
    dependent tinyint NOT NULL,
    health_insur_num varchar(15),
    nationality varchar(40),
    empl_insur_insur_qual_acq_date date,
    empl_insur_insur_qual_lost_date date,
    soc_insur_insur_qual_acq_date date,
    soc_insur_insur_qual_lost_date date,
    start date,
    end date,
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    memo varchar(100),
    PRIMARY KEY (id)
);

CREATE TABLE m_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int NOT NULL,
    base int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    income_tax int,
    inhabitant_tax int,
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_calendar (
    id int NOT NULL AUTO_INCREMENT,
    ymd date NOT NULL,
    year int NOT NULL,
    month int NOT NULL,
    day int NOT NULL,
    day_of_week varchar(3) NOT NULL,
    visiblr_flg tinyint NOT NULL,
    working_st tinyint NOT NULL,
    memo varchar(100),
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_jobshift (
    id int NOT NULL AUTO_INCREMENT,
    shift_name varchar(40) NOT NULL,
    delete_flg tinyint NOT NULL,
    job_type int NOT NULL,
    work_in_time time NOT NULL,
    work_out_time time NOT NULL,
    rest time NOT NULL,
    memo varchar(99),
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE m_admin (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int NOT NULL,
    admin_id varchar(30) NOT NULL,
    password varchar(200) NOT NULL,
    fail_count int,
    edit_flg tinyint,
    attend_flg tinyint,
    vacation_flg tinyint,
    employee_flg tinyint,
    calendar_flg tinyint,
    shift_flg tinyint,
    payment_flg tinyint,
    start date,
    end date,
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_attends (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int NOT NULL,
    working_st tinyint NOT NULL,
    round_work_in_time datetime NOT NULL,
    work_in datetime NOT NULL,
    round_work_out_time datetime,
    work_out datetime,
    work_time time,
    rest time NOT NULL,
    orvertime time,
    nighttime time,
    holiday_time time,
    create_at datetime,
    create_acc int,
    create_mac varchar(20),
    update_at datetime,
    update_acc int,
    update_mac varchar(20),
    PRIMARY KEY (id)
);

CREATE TABLE t_paidvacasubm (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int NOT NULL,
    subm_date datetime NOT NULL,
    target_date date NOT NULL,
    subm_st tinyint NOT NULL,
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);

CREATE TABLE t_payments (
    id int NOT NULL AUTO_INCREMENT,
    employee_id int NOT NULL,
    payment_date date NOT NULL,
    income int NOT NULL,
    base int,
    overtime_pay int,
    nighttime_pay int,
    holiday_pay int,
    commuting_pay int,
    health_insur int,
    care_insur int,
    pension_insur int,
    employee_insur int,
    income_tax int,
    inhabitant_tax int,
    withholding_tax int,
    adj_pay int,
    others int,
    create_at datetime NOT NULL,
    create_acc int NOT NULL,
    update_at datetime,
    update_acc int,
    PRIMARY KEY (id)
);